export const STARTING_RUNNING_BALANCE_USDT = 1000

export const VOLATILE_MARKET_SYMBOL_LIMIT = 25

export const DEFAULT_PREFERRED_SYMBOLS = [
  'BTCUSDT',
  'ETHUSDT',
  'SOLUSDT',
  'XRPUSDT',
  'DOGEUSDT',
  'BNBUSDT',
  'ADAUSDT',
  'AVAXUSDT',
  'LINKUSDT',
  'LTCUSDT',
  'SUIUSDT',
  'TRXUSDT',
  'DOTUSDT',
  'NEARUSDT',
  'TAOUSDT',
  'FETUSDT',
  '1000PEPEUSDT',
  'PIXELUSDT',
  'TURBOUSDT',
  'TRUMPUSDT',
  'APTUSDT',
  'ARBUSDT',
  'INJUSDT',
  'WLDUSDT',
  'HBARUSDT',
]
